### ISSUE TITLE
Building GNU Radio without OpenGL/X?

### ISSUE THREAD

**Issue by njpillitteri** [balister/meta-sdr#15] opened 2015-04-04 23:09 UTC
Is it possible to build GNU Radio without including OpenGL and X in the file system. For example, could I build an RFS for the Ettus E310 or a similar device with GNU Radio support, but none of the huge graphics libraries that these devices don't need.

**Comment by balister** [comment] 2015-04-05 02:06
It should be. If it isn't there is something I need to fix. You will
need to look at DISTRO_FEATURES and PACKAGECONFIG options for gnuradio.

I'll see about testing this case next week.

Philip

**Comment by njpillitteri** [comment] 2015-04-05 13:40
I personally wasn't able to build it without "DISTRO_FEATURES_append= "opengl x11"" in my local.conf. I removed gr-osmosdir and gr-eventstream from packagegroup-sdr-gnuradio but still had issues. I'm also not building packagegroup-sdr-hardware.

Im up to date on the master branches of meta-sdr, meta-openembedded, meta-xilinx, and openembedded-core.

If I figure it out I'll let you know.

**Comment by trondeau** [comment] 2015-04-06 13:14
In my local.conf file, I removed DISTRO_FEATURES entirely and also had to change the package config options for gnuradio by removing 'grc' and 'qtgui':

#DISTRO_FEATURES_append = " opengl x11"
PACKAGECONFIG_pn-gnuradio = "uhd zeromq"

I also had to remove the references to gnuradio-grc and gnuradio-qtgui in GR_PACKAGES in the gnuradio_git.bb file itself since it uses a strong setter.

**Comment by balister** [comment] 2015-04-06 17:16
So the issue is you get empty packages for the grc and qtgui packages,
but the have REDEPENDS on x11 based stuff? Or do I need to PACKAGECONFIG
grc? /me goes to check if it is already.

**Comment by balister** [comment] 2015-06-19 19:26
I think I have stuff in place for this now.

**Comment by njpillitteri** [comment] 2015-06-19 20:18
I'm trying now. I'll let you know.

**Comment by balister** [comment] 2015-06-19 20:47
You will need to tweak the PACKAGECONFIG options on gnuradio. It isn't
automatic, but it should work now.

**Comment by balister** [comment] 2016-05-18 13:06
Pretty sure this has been fixed, closing

**Closed by balister** 2016-05-18 13:06 UTC
